### ISSUE TITLE
此项目Python版本应在3.10-3.12.2之间，其他版本会报错

### ISSUE THREAD

**Issue by hujihan** [amdoi7/ZJOOCHelper#2]
如何正常使用？
`Traceback (most recent call last):
  File "C:\Users\hjh\Downloads\VideoBot-master\VideoBot\ZJOOCHelper-master\main.py", line 1, in <module>
    from zjooc import ZJOOC
  File "C:\Users\hjh\Downloads\VideoBot-master\VideoBot\ZJOOCHelper-master\zjooc.py", line 411
    match commond_sets[0]:
          ^
SyntaxError: invalid syntax`

**Comment by amdoi7** [comment]
match commond_sets[0]: ^ SyntaxError: invalid syntax 说明你的python版本不支持 match 语法 match 好像是3.9还是3.10出来的 好像有些电脑默认是3.8的  你查看一下你的Python版本

**Comment by hujihan** [comment]
那请问大佬哪个python版本可以正常使用？3.8吗

**Comment by hujihan** [comment]
我用的是3.9.8版本

**Comment by hujihan** [comment]
使用python3.12还是报错
![image](https://github.com/amdoi7/ZJOOCHelper/assets/46958243/9ae175c7-bd3e-4d94-b66a-927c051bb868)


```
C:\Users\hjh\AppData\Local\Programs\Python\Python312\python.exe C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\main.py 
Traceback (most recent call last):
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\main.py", line 22, in <module>
    user = ZJOOC(username="", pwd="")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\zjooc.py", line 37, in __init__
    self.login(username, pwd)
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\zjooc.py", line 46, in login
    captcha_code = ocr.classification(base64.b64decode((captcha_data["image"])))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hjh\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddddocr\__init__.py", line 466, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
                                                                          ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

进程已结束，退出代码为 1
``` 


还有，新建的python文件里面需要如何填写，在22行填写了账号密码之后还是一样的报错

```
C:\Users\hjh\AppData\Local\Programs\Python\Python312\python.exe C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\main.py 
Traceback (most recent call last):
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\main.py", line 22, in <module>
    user = ZJOOC(username="1313***666", pwd="x****g1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\zjooc.py", line 37, in __init__
    self.login(username, pwd)
  File "C:\Users\hjh\Downloads\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\zjooc.py", line 46, in login
    captcha_code = ocr.classification(base64.b64decode((captcha_data["image"])))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hjh\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddddocr\__init__.py", line 466, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
                                                                          ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

进程已结束，退出代码为 1
```

**Comment by amdoi7** [comment]
emm 好像是我的ddddocr的包版本没有更新你 pip uninstall ddddocr然后在pip install ddddocr 重装一下？ 或者等我有时间上传hhh

**Comment by hujihan** [comment]
还是不行

**Comment by hujihan** [comment]
运行是没问题了，但是刷完虽然显示打勾了，但是实际观看时间没有。导致视频观看分为0

**Comment by hujihan** [comment]
今天手贱重装了一下Python，现在不管换哪个版本都这样
`ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


Traceback (most recent call last):
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\main.py", line 1, in <module>
    from zjooc import ZJOOC
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\zjooc.py", line 5, in <module>
    import ddddocr
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\venv\Lib\site-packages\ddddocr\__init__.py", line 10, in <module>
    import onnxruntime
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\venv\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>       
    raise import_capi_exception
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\venv\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>       
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\学习通刷课\在浙学刷课\ZJOOCHelper-master\ZJOOCHelper-master\pythonProject\venv\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError
`
